// SPDX-FileCopyrightText: 2026 Frogfish
// SPDX-License-Identifier: Apache-2.0
// Author: Alexander Croft <alex@frogfish.io>

//! Minimal unsafe Hopper FFI bindings generated by bindgen.
//! To regenerate, run `cargo build`.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Safe wrapper around hopper_version.
pub fn version() -> u32 {
    unsafe { hopper_version() }
}
