// SPDX-FileCopyrightText: 2026 Frogfish
// SPDX-License-Identifier: Apache-2.0
// Author: Alexander Croft <alex@frogfish.io>

//! Minimal Hopper bindings generated by bindgen.
//! To regenerate, run `cargo build`.
//!
//! The raw FFI is available under the `ffi` module. Simple safe helpers are
//! provided for frequently used constants and sizes.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub mod ffi {
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

/// Safe wrapper around `hopper_version()`.
pub fn version() -> u32 {
    unsafe { ffi::hopper_version() }
}

/// Safe wrapper around `hopper_sizeof()`.
pub fn ctx_size() -> usize {
    unsafe { ffi::hopper_sizeof() as usize }
}

/// Safe wrapper around `hopper_ref_entry_sizeof()`.
pub fn ref_entry_size() -> usize {
    unsafe { ffi::hopper_ref_entry_sizeof() as usize }
}
